### ISSUE TITLE
Redundant newline at the end of generated modules

### ISSUE THREAD

**Issue by tomhoule** [tomhoule/purescript-waterslide-rs#38]

**Comment by Borginator** [comment]
Hi, I'd like to submit a pull request for this issue but I'm getting permission denied to my account.
I'm new to open source so if there's something you need me to do first let me know!
error:

```
remote: Permission to tomhoule/purescript-waterslide-rs.git denied to Borginator.
fatal: unable to access 'https://github.com/tomhoule/purescript-waterslide-rs.git/': The requested URL returned error: 403
```

**Comment by tomhoule** [comment]
Hi! Thanks for wanting to contribute :)

I think you need to:

- fork the repository (with the "fork" button on the top-right of the github page)
- then point to your fork (with something like `git remote set-url origin https://github.com/Borginator/purescript-waterslide-rs` in your local directory)
- then git push to the fork
- finally, you can visit the repository on github and there should be a button to open a pull request against this one

[This page](https://gist.github.com/Chaser324/ce0505fbed06b947d962) has more in-depth explanations.

I can help more if needed, don't hesitate to ask!

**Comment by Borginator** [comment]
Thanks for the instructions! Pull request submitted.
